# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        config:
          - { os: ubuntu-22.04, compiler: gcc, profile: debug }
          - { os: ubuntu-22.04, compiler: gcc, profile: release }

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

        - name: Installing system packages
      run: sudo apt-get -y update &&
           sudo apt-get install python3 pip g++-12 flex bison libfl-dev

    - name: Installing conan and setting venv
      run: python3 -m venv .venv;
           source .venv/bin/activate;
           echo PATH=$PATH >> $GITHUB_ENV;
           pip install conan==2.12.1;

    - name: Installing conan requirements
      run: >
        conan profile detect --force;
        conan install .
        --profile=.conan/profiles/${{ matrix.config.profile }}
        --output-folder=build
        --build=missing
        --settings compiler=${{ matrix.config.compiler }}

    - name: Configure CMake
      run: >
        cmake . -B build --preset conan-${{ matrix.config.profile }}

    - name: Build
      run:
        cmake --build build -j

    - name: Test
      if: ${{ matrix.config.profile == 'debug' }}
      run: ctest --output-on-failure --test-dir build --no-tests=error
